name = "stripeflare-cli"
main = "main.ts"
assets.directory = "./"
compatibility_date = "2025-06-06"

dev.port = 3000
routes = [
  { pattern = "img.brubslabs.com", custom_domain = true }
]

[[durable_objects.bindings]]
name = "DORM_NAMESPACE"
class_name = "DORM"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DORM"]

# wrangler.toml
[[r2_buckets]]
bucket_name = "stripeimages"
binding = "stripeimages"

[vars]
R2_PUBLIC_URL = "https://image.brubslabs.com"